name: CI
on:
  push:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sanity checks
        run: |
          set -e
          test -f README.md || (echo "README.md missing" && exit 1)
          test -f LICENSE || (echo "LICENSE missing" && exit 1)
          test -d images || (echo "images/ folder missing" && exit 1)
          [ "$(ls -A images || true)" ] || (echo "images/ is empty" && exit 1)
